//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteratureApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Literature
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Literature()
        {
            this.Book = new HashSet<Book>();
        }
    
        public int LitId { get; set; }
        public string Name { get; set; }
        public int GenerId { get; set; }
        public int AuthorId { get; set; }
        public int PublisherId { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Raiting { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
    
        public virtual Author Author { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book> Book { get; set; }
        public virtual Gener Gener { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
