//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteratureApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageMarks
    {
        public int PageMarkId { get; set; }
        public int BookId { get; set; }
        public int UserId { get; set; }
        public int Page { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Users Users { get; set; }
    }
}
